Feature/comparable versions
questionpy-org/questionpy-common pull request #13
Opened 2023-03-22 12:20 UTC by janbritz

Closes #12.

Kann z.B. im SDK verwendet werden, um nach dem aktuellsten Manifest zu filtern.

2023-03-23 11:46 UTC, MartinGauk requested changes

2023-03-23 11:46 UTC, MartinGauk commented on pyproject.toml
> +semver = "^2.13.0"
Bitte keine weiteren externen Abhängigkeiten. Das common Paket war dazu gedacht schlank zu sein und nur Definitionen zu enthalten.
Wir hatten damals eine lange Diskussion gehabt, welche Abhängigkeiten wir den Paketen/Workern überhaupt vorschreiben können und hatten entschieden nur pydantic als notwendigste externe Abhängigkeit zu verwenden. Das bedeutet auch, dass wir pydantic-factories irgendwann noch entfernen müssen.

2023-03-28 09:28 UTC, janbritz commented on pyproject.toml
> +semver = "^2.13.0"
Ich habe die Abhängigkeit entfernt und noch eine kleine Anmerkung hinzugefügt.

2023-03-29 11:38 UTC, MHajoha approved these changes

2023-03-29 11:38 UTC, MHajoha commented on questionpy_common/version.py
> +        return self._lt(other)
* Wenn `other` inkompatibel ist, sollte hier nicht `NotImplementedError` geworfen werden, sondern `NotImplemented` zurückgegeben werden: <https://docs.python.org/3/reference/datamodel.html#object.__lt__>
* Das muss wirklich nicht rekursiv sein. Vorschlag:
  ```python
  if not isinstance(other, _ComparableVersion) or self._length != other._length:
      return NotImplemented

  for left, right in zip(self._parts, other._parts):
      if left < right:
          return True
      if left > right:
          return False
  return False
  ```

2023-04-11 10:19 UTC, closed without merging